//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Sex { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> FirstDateCome { get; set; }
        public Nullable<int> IdTag { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
