//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStaff
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public Nullable<int> SeriaPas { get; set; }
        public Nullable<int> NumberPas { get; set; }
        public Nullable<int> IdCode { get; set; }
        public string Sex { get; set; }
        public Nullable<int> KoefOplata { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<int> IdCategoryEmployeeStaff { get; set; }
    
        public virtual CategoryEmployeeStaff CategoryEmployeeStaff { get; set; }
    }
}
