//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryServiceClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntryServiceClient()
        {
            this.EntryServiceClientFile = new HashSet<EntryServiceClientFile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryServiceClientFile> EntryServiceClientFile { get; set; }
    }
}
