//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryServiceClientFile
    {
        public int id { get; set; }
        public string File { get; set; }
        public Nullable<int> IdEntryServiceClient { get; set; }
    
        public virtual EntryServiceClient EntryServiceClient { get; set; }
    }
}
