//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schoolEntities : DbContext
    {
        public schoolEntities()
            : base("name=schoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryEmployeeStaff> CategoryEmployeeStaff { get; set; }
        public virtual DbSet<CategoryProduct> CategoryProduct { get; set; }
        public virtual DbSet<CharacteristicProduct> CharacteristicProduct { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Code> Code { get; set; }
        public virtual DbSet<EmployeeStaff> EmployeeStaff { get; set; }
        public virtual DbSet<EntryServiceClient> EntryServiceClient { get; set; }
        public virtual DbSet<EntryServiceClientFile> EntryServiceClientFile { get; set; }
        public virtual DbSet<HistoryPurchase> HistoryPurchase { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductOtherPhoto> ProductOtherPhoto { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceOtherPhoto> ServiceOtherPhoto { get; set; }
        public virtual DbSet<SizeProduct> SizeProduct { get; set; }
        public virtual DbSet<StatusProduct> StatusProduct { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
    }
}
