//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.HistoryPurchase = new HashSet<HistoryPurchase>();
            this.ProductOtherPhoto = new HashSet<ProductOtherPhoto>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Cost { get; set; }
        public Nullable<int> IdCharacteristicsProduct { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdSizeProduct { get; set; }
        public Nullable<int> Weidth { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public string MainPhoto { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual CharacteristicProduct CharacteristicProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryPurchase> HistoryPurchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOtherPhoto> ProductOtherPhoto { get; set; }
    }
}
