//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Windows.Media.Imaging;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceOtherPhoto = new HashSet<ServiceOtherPhoto>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullDescription { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Countinios { get; set; }
        public string MainPhoto { get; set; }

        [NotMapped]
        public int? CostWithSale => Sale != null ? Cost - (Cost * Sale / 100) : Cost;

        [NotMapped]
        public string CostS => Sale.HasValue  ? $"Цена без скидки {Cost}, со скидкой " : "";

        [NotMapped]
        public string FullCost => CostS + CostWithSale.ToString() + " рублей за " + Countinios.ToString() + " минут";

        [NotMapped]
        public string fileNameWithPhoto => !MainPhoto.Contains("Photos") ? string.Join("\\", new List<string>() { "Photos", MainPhoto }) : MainPhoto;

        [NotMapped]
        public BitmapImage MainPhotoImage => !string.IsNullOrEmpty(MainPhoto) ? new BitmapImage(new Uri("C:\\Users\\User\\source\\repos\\schoolWork\\schoolWork\\schoolWork\\" + fileNameWithPhoto)) : null;

        [NotMapped]

        public string SaleText => Sale.HasValue ? $"* скидка {Sale}%" : "";

        

      



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOtherPhoto> ServiceOtherPhoto { get; set; }
    }
}
