//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Windows.Media.Imaging;

    public partial class ServiceOtherPhoto
    {
        public int Id { get; set; }
        public string Photo { get; set; }

        [NotMapped]
        public string fileNameWithPhoto => !Photo.Contains("Photos") ? string.Join("\\", new List<string>() { "Photos", Photo }) : Photo;

        [NotMapped]
        public BitmapImage MainPhotoImage => !string.IsNullOrEmpty(Photo) ? new BitmapImage(new Uri("C:\\Users\\User\\source\\repos\\schoolWork\\schoolWork\\schoolWork\\" + fileNameWithPhoto)) : null;


        public Nullable<int> IdService { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
